# Generated by Django 4.0.4 on 2022-06-02 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_alter_stock_max_alter_stock_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
