# Generated by Django 4.0.4 on 2022-06-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_alter_alarmstock_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmstock',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='alarmstock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
