# Generated by Django 4.0.4 on 2022-06-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0009_alter_stock_created_date_alter_stock_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmstock',
            name='stock',
        ),
    ]
