# Generated by Django 4.0.4 on 2022-06-02 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0011_remove_alarmstock_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmstock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.stock'),
        ),
    ]
