# Generated by Django 4.0.4 on 2022-06-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0021_alter_stock_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='created_date',
            field=models.DateTimeField(default=None),
        ),
    ]
