# Generated by Django 4.0.4 on 2022-06-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0028_stock_price_alter_stock_max_alter_stock_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmstock',
            name='buying_at',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='alarmstock',
            name='selling_at',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stock',
            name='max',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='stock',
            name='min',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=303),
        ),
    ]
