# Generated by Django 4.0.4 on 2022-06-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0029_alter_alarmstock_buying_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='variance',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='variance_percentage',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
