# Generated by Django 4.0.4 on 2022-06-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0032_alarmstock_created_at_alarmstock_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmstock',
            name='status',
            field=models.CharField(default='Stand by..', max_length=20, unique=True),
        ),
    ]
