# Generated by Django 4.0.4 on 2022-06-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='max',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='stock',
            name='min',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
