# Generated by Django 4.0.4 on 2022-06-02 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scraping', '0005_alter_stock_created_date_alter_stock_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True),
        ),
        migrations.CreateModel(
            name='AlarmStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_at', models.DecimalField(decimal_places=3, max_digits=5)),
                ('selling_at', models.DecimalField(decimal_places=3, max_digits=5)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, unique=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['stock'],
            },
        ),
    ]
