# Generated by Django 4.0.4 on 2022-06-02 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0010_remove_alarmstock_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmstock',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='alarmstock',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='alarmstock',
            name='stock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scraping.stock'),
        ),
    ]
