# Generated by Django 4.0.4 on 2022-06-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0014_alter_stock_created_date_alter_stock_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmstock',
            name='stock',
        ),
        migrations.AlterField(
            model_name='stock',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
