# Generated by Django 4.0.4 on 2022-06-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0015_remove_alarmstock_stock_alter_stock_created_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlarmStock',
        ),
    ]
