# Generated by Django 4.0.4 on 2022-06-03 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scraping', '0026_stock_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_at', models.DecimalField(decimal_places=3, max_digits=5)),
                ('selling_at', models.DecimalField(decimal_places=3, max_digits=5)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
