# Generated by Django 4.0.4 on 2022-06-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0027_alarmstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='max',
            field=models.DecimalField(decimal_places=3, max_digits=30),
        ),
        migrations.AlterField(
            model_name='stock',
            name='min',
            field=models.DecimalField(decimal_places=3, max_digits=30),
        ),
    ]
