# Generated by Django 4.0.4 on 2022-06-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0030_stock_variance_stock_variance_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='url',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
