# Generated by Django 4.0.4 on 2022-06-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0031_stock_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmstock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmstock',
            name='status',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='alarmstock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
